login: &login
  adapter: postgresql
  encoding: utf8
  reconnect: false
  username: testing1
  password: 'qwe123'
  host: localhost
  port: 5432

development:
  <<: *login
  database: bdtesting1_development

test:
  <<: *login
  database: bdtesting1_test

production:
  <<: *login
  dtabase: bdtesting1_prodaction